<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="33" time="2.471" timestamp="2025-07-01T20:23:43.715950+10:00" hostname="DESKTOP-0Q8HRTN"><testcase classname="tests.test_favourites" name="test_load_favourites_file_not_found" file="tests\test_favourites.py" line="10" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_favourites" name="test_load_favourites_json_error" file="tests\test_favourites.py" line="30" time="0.006"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_favourites" name="test_load_favourites_success" file="tests\test_favourites.py" line="20" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_favourites" name="test_save_favourite_add_new_city" file="tests\test_favourites.py" line="42" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_favourites" name="test_save_favourite_empty_city_string" file="tests\test_favourites.py" line="62" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_favourites" name="test_save_favourite_non_string_input" file="tests\test_favourites.py" line="72" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_favourites" name="test_save_favourite_remove_existing_city" file="tests\test_favourites.py" line="52" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_main" name="test_on_close_calls_destroy_and_logs" file="tests\test_main.py" line="24" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_main" name="test_on_select_favourite_triggers_search_and_update" file="tests\test_main.py" line="8" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_ui_components" name="test_handle_search_location_not_found" file="tests\test_ui_components.py" line="76" time="0.147"><system-out>--------------------------------- Captured Log ---------------------------------
ERROR    WeatherViewLogger:ui_components.py:150 Could not update UI: KeyError - 'condition'
--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_ui_components" name="test_handle_search_success" file="tests\test_ui_components.py" line="34" time="0.101"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_ui_components" name="test_load_weather_icon_fallback_to_default" file="tests\test_ui_components.py" line="114" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_ui_components" name="test_load_weather_icon_success" file="tests\test_ui_components.py" line="100" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_create_forecast_figure" file="tests\test_utils.py" line="91" time="0.090"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_get_user_city_failure" file="tests\test_utils.py" line="126" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_get_user_city_success" file="tests\test_utils.py" line="110" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_on_remove_favourite" file="tests\test_utils.py" line="53" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_on_save_favourite_new_city" file="tests\test_utils.py" line="27" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_set_dynamic_background[clear]" file="tests\test_utils.py" line="70" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_set_dynamic_background[drizzle]" file="tests\test_utils.py" line="70" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_set_dynamic_background[few clouds]" file="tests\test_utils.py" line="70" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_set_dynamic_background[light snow]" file="tests\test_utils.py" line="70" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_set_dynamic_background[mist]" file="tests\test_utils.py" line="70" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_set_dynamic_background[shower rain]" file="tests\test_utils.py" line="70" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_set_dynamic_background[thunderstorms]" file="tests\test_utils.py" line="70" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_set_dynamic_background[unknown condition]" file="tests\test_utils.py" line="70" time="0.009"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_utils" name="test_update_fav_button_city_is_favourite" file="tests\test_utils.py" line="42" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_weather_api" name="test_extract_daily_min_max" file="tests\test_weather_api.py" line="114" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_weather_api" name="test_get_detailed_forecast_by_city_success" file="tests\test_weather_api.py" line="91" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_weather_api" name="test_get_forecast_by_city_success" file="tests\test_weather_api.py" line="68" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_weather_api" name="test_get_weather_by_city_not_found" file="tests\test_weather_api.py" line="44" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------
ERROR    WeatherViewLogger:weather_api.py:29 Could not find location in get_weather_by_city
--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_weather_api" name="test_get_weather_by_city_request_fails" file="tests\test_weather_api.py" line="55" time="0.003"><failure message="AssertionError: assert 'Location not found.' == 'Request failed.'&#10;  &#10;  - Request failed.&#10;  + Location not found.">mock_requests_get = &lt;MagicMock name='get()' id='2141412108544'&gt;

    def test_get_weather_by_city_request_fails(mock_requests_get):
        """
        Tests handling of a network failure during the API request.
        """
        mock_requests_get.side_effect = Exception("Network Error")
    
        result = weather_api.get_weather_by_city("London", "metric")
    
        assert "error" in result
&gt;       assert result["error"] == "Request failed."
E       AssertionError: assert 'Location not found.' == 'Request failed.'
E         
E         - Request failed.
E         + Location not found.

tests\test_weather_api.py:65: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------
ERROR    WeatherViewLogger:weather_api.py:29 Could not find location in get_weather_by_city
--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_weather_api" name="test_get_weather_by_city_success" file="tests\test_weather_api.py" line="23" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>